name = "A Cobblemon Pack that Isn't Mid"
author = "violetshiver"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96fb10576ad378e2cfecaf11ed5d031c1422256d13eb85d97a2d22255daa12a1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21.1"]
